# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-TabFile
version:      1.10
version_from: lib/Text/TabFile.pm
installdirs:  site
requires:
    Text::Delimited:               2.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
